In [73]:
import pandas as pd
import numpy as np
import itertools
import operator
import functools
from code_and_data_for_hw3 import code_for_hw3_part1 as p1
from code_and_data_for_hw3 import code_for_hw3_part2 as p2

In [5]:
data = np.array([[2, 3, 4, 5]])
labels = np.array([[1, 1, -1, -1]])

In [6]:
def one_hot(x, k):
    arr = np.zeros(k)
    arr[x-1] = 1
    return np.array([arr]).T

In [7]:
data = np.zeros((6, 6))
for i in range(6):
    data[:, i:i+1] = one_hot(i+1, 6)
labels = np.array([[1, 1, -1, -1, 1, 1]])
data

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [8]:
p1.perceptron(data, labels)

(array([[ 1.],
        [ 1.],
        [-2.],
        [-2.],
        [ 1.],
        [ 1.]]),
 array([[0.]]))

In [ ]:
p1.make_polynomial_feature_fun(2)(np.zeros((10, 1))).shape

In [28]:
auto_data_all = p2.load_auto_data("./lab3_data/auto-mpg.tsv")
features = [('cylinders', p2.raw),
            ('displacement', p2.raw),
            ('horsepower', p2.raw),
            ('weight', p2.raw),
            ('acceleration', p2.raw),
            ## Drop model_year by default
            ## ('model_year', hw3.raw),
            ('origin', p2.raw)]

features2 = [('cylinders', p2.one_hot),
            ('displacement', p2.standard),
            ('horsepower', p2.standard),
            ('weight', p2.standard),
            ('acceleration', p2.standard),
            ## Drop model_year by default
            ## ('model_year', hw3.raw),
            ('origin', p2.one_hot)]

In [71]:
auto_data, auto_labels = p2.auto_data_and_labels(auto_data_all, features2)
print(auto_data.shape)
print(auto_labels.shape)
#p2.xval_learning_alg(p2.averaged_perceptron, auto_data, auto_labels, 10)

avg and std {'displacement': (388.3482142857143, 302.0458123396403), 'horsepower': (509.3545918367347, 333.6521151716361), 'weight': (2977.5841836734694, 848.3184465698365), 'acceleration': (15.541326530612228, 2.7553429127509963)}
entries in one_hot field {'cylinders': [3.0, 4.0, 5.0, 6.0, 8.0], 'origin': [1.0, 2.0, 3.0]}
(12, 392)
(1, 392)


In [39]:
p2.averaged_perceptron(auto_data, auto_labels)

(array([[-2.20586735],
        [ 0.31283163],
        [ 0.6892602 ],
        [-0.93739796],
        [ 2.8592602 ],
        [-1.42199522],
        [ 0.28864298],
        [-6.72622777],
        [ 0.84545478],
        [-0.10834184],
        [ 1.42637755],
        [-0.59994898]]),
 array([[0.71808673]]))

In [74]:
test = p2.load_review_data("./lab3_data/reviews.tsv")
text = []
review_labels = np.array([np.zeros(len(test))])
for stuff in test:
    text.append(stuff["text"])
for i in range(len(test)):
    review_labels[0, i] = test[i]["sentiment"]
rah = p2.bag_of_words(text)
review_data = p2.extract_bow_feature_vectors(text, rah)

In [75]:
print(review_labels.shape)
print(review_data.shape)

p2.xval_learning_alg(p2.averaged_perceptron, review_labels, review_data, 10)

(1, 10000)
(19945, 10000)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()