In [23]:
import importlib
import pandas as pd
import numpy as np
import itertools
import operator
import functools
from code_and_data_for_hw3 import code_for_hw3_part1 as p1
from code_and_data_for_hw3 import code_for_hw3_part2 as p2
importlib.reload(p1)
importlib.reload(p2)

Importing code_for_hw03
Imported tidy_plot, plot_separator, plot_data, plot_nonlin_sep, cv, rv, y, positive, score
Datasets: super_simple_separable_through_origin(), super_simple_separable(), xor(), xor_more()
Tests for part 2: test_linear_classifier_with_features, mul, make_polynomial_feature_fun, 
                  test_with_features
Also loaded: perceptron, one_hot_internal, test_one_hot
Importing code_for_hw03 (part 2, imported as hw3)
Imported tidy_plot, plot_separator, plot_data, plot_nonlin_sep, cv, rv, y, positive, score
         xval_learning_alg, eval_classifier
Tests: test_linear_classifier
Dataset tools: load_auto_data, std_vals, standard, raw, one_hot, auto_data_and_labels
               load_review_data, clean, extract_words, bag_of_words, extract_bow_feature_vectors
               load_mnist_data, load_mnist_single


<module 'code_and_data_for_hw3.code_for_hw3_part2' from 'c:\\Users\\jiama\\Documents\\ocw\\week3\\code_and_data_for_hw3\\code_for_hw3_part2.py'>

In [3]:
data = np.array([[2, 3, 4, 5]])
labels = np.array([[1, 1, -1, -1]])

In [4]:
def one_hot(x, k):
    arr = np.zeros(k)
    arr[x-1] = 1
    return np.array([arr]).T

In [5]:
data = np.zeros((6, 6))
for i in range(6):
    data[:, i:i+1] = one_hot(i+1, 6)
labels = np.array([[1, 1, -1, -1, 1, 1]])
data

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [6]:
p1.perceptron(data, labels)

(array([[ 1.],
        [ 1.],
        [-2.],
        [-2.],
        [ 1.],
        [ 1.]]),
 array([[0.]]))

In [7]:
p1.make_polynomial_feature_fun(2)(np.zeros((10, 1))).shape

(66, 1)

In [8]:
auto_data_all = p2.load_auto_data("./lab3_data/auto-mpg.tsv")
features = [('cylinders', p2.raw),
            ('displacement', p2.raw),
            ('horsepower', p2.raw),
            ('weight', p2.raw),
            ('acceleration', p2.raw),
            ## Drop model_year by default
            ## ('model_year', hw3.raw),
            ('origin', p2.raw)]

features2 = [('cylinders', p2.one_hot),
            ('displacement', p2.standard),
            ('horsepower', p2.standard),
            ('weight', p2.standard),
            ('acceleration', p2.standard),
            ## Drop model_year by default
            ## ('model_year', hw3.raw),
            ('origin', p2.one_hot)]

In [9]:
auto_data, auto_labels = p2.auto_data_and_labels(auto_data_all, features2)
print(auto_data.shape)
print(auto_labels.shape)
#p2.xval_learning_alg(p2.averaged_perceptron, auto_data, auto_labels, 10)

avg and std {'displacement': (388.3482142857143, 302.0458123396403), 'horsepower': (509.3545918367347, 333.6521151716361), 'weight': (2977.5841836734694, 848.3184465698365), 'acceleration': (15.541326530612228, 2.7553429127509963)}
entries in one_hot field {'cylinders': [3.0, 4.0, 5.0, 6.0, 8.0], 'origin': [1.0, 2.0, 3.0]}
(12, 392)
(1, 392)


In [10]:
p2.averaged_perceptron(auto_data, auto_labels)

(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1)

(array([[-0.92168367],
        [ 1.50280612],
        [ 0.40229592],
        [-0.7630102 ],
        [ 0.73903061],
        [-1.17833746],
        [ 0.45228459],
        [-4.91225636],
        [ 0.45783691],
        [ 0.27806122],
        [ 0.97091837],
        [-0.28954082]]),
 array([[0.95943878]]))

In [11]:
test = p2.load_review_data("./lab3_data/reviews.tsv")
text = []
review_labels = np.array([np.zeros(len(test))])
for stuff in test:
    text.append(stuff["text"])
for i in range(len(test)):
    review_labels[0, i] = test[i]["sentiment"]
rah = p2.bag_of_words(text)
review_data = p2.extract_bow_feature_vectors(text, rah)

In [24]:
# print(review_labels.shape)
# print(review_data.shape)

# review_labels[:, 1:2]
print(p2.xval_learning_alg(p2.perceptron, review_data, review_labels, 10))
print(p2.xval_learning_alg(p2.averaged_perceptron, review_data, review_labels, 10))
#p2.xval_learning_alg(p2.averaged_perceptron, review_data, review_labels, 10)

0.7871
0.8237
