In [64]:
import importlib
import pandas as pd
import numpy as np
import itertools
import operator
import functools
from code_and_data_for_hw3 import code_for_hw3_part1 as p1
from code_and_data_for_hw3 import code_for_hw3_part2 as p2
importlib.reload(p1)
importlib.reload(p2)

Importing code_for_hw03
Imported tidy_plot, plot_separator, plot_data, plot_nonlin_sep, cv, rv, y, positive, score
Datasets: super_simple_separable_through_origin(), super_simple_separable(), xor(), xor_more()
Tests for part 2: test_linear_classifier_with_features, mul, make_polynomial_feature_fun, 
                  test_with_features
Also loaded: perceptron, one_hot_internal, test_one_hot
Importing code_for_hw03 (part 2, imported as hw3)


<module 'code_and_data_for_hw3.code_for_hw3_part2' from 'c:\\Users\\jiama\\Documents\\ocw\\week3\\code_and_data_for_hw3\\code_for_hw3_part2.py'>

In [3]:
data = np.array([[2, 3, 4, 5]])
labels = np.array([[1, 1, -1, -1]])

In [4]:
def one_hot(x, k):
    arr = np.zeros(k)
    arr[x-1] = 1
    return np.array([arr]).T

In [5]:
data = np.zeros((6, 6))
for i in range(6):
    data[:, i:i+1] = one_hot(i+1, 6)
labels = np.array([[1, 1, -1, -1, 1, 1]])
data

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [6]:
p1.perceptron(data, labels)

(array([[ 1.],
        [ 1.],
        [-2.],
        [-2.],
        [ 1.],
        [ 1.]]),
 array([[0.]]))

In [7]:
p1.make_polynomial_feature_fun(2)(np.zeros((10, 1))).shape

(66, 1)

In [8]:
auto_data_all = p2.load_auto_data("./lab3_data/auto-mpg.tsv")
features = [('cylinders', p2.raw),
            ('displacement', p2.raw),
            ('horsepower', p2.raw),
            ('weight', p2.raw),
            ('acceleration', p2.raw),
            ## Drop model_year by default
            ## ('model_year', hw3.raw),
            ('origin', p2.raw)]

features2 = [('cylinders', p2.one_hot),
            ('displacement', p2.standard),
            ('horsepower', p2.standard),
            ('weight', p2.standard),
            ('acceleration', p2.standard),
            ## Drop model_year by default
            ## ('model_year', hw3.raw),
            ('origin', p2.one_hot)]

In [9]:
auto_data, auto_labels = p2.auto_data_and_labels(auto_data_all, features2)
print(auto_data.shape)
print(auto_labels.shape)
#p2.xval_learning_alg(p2.averaged_perceptron, auto_data, auto_labels, 10)

avg and std {'displacement': (388.3482142857143, 302.0458123396403), 'horsepower': (509.3545918367347, 333.6521151716361), 'weight': (2977.5841836734694, 848.3184465698365), 'acceleration': (15.541326530612228, 2.7553429127509963)}
entries in one_hot field {'cylinders': [3.0, 4.0, 5.0, 6.0, 8.0], 'origin': [1.0, 2.0, 3.0]}
(12, 392)
(1, 392)


In [10]:
p2.averaged_perceptron(auto_data, auto_labels)

(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1) (1, 1)
(1, 1)

(array([[-0.92168367],
        [ 1.50280612],
        [ 0.40229592],
        [-0.7630102 ],
        [ 0.73903061],
        [-1.17833746],
        [ 0.45228459],
        [-4.91225636],
        [ 0.45783691],
        [ 0.27806122],
        [ 0.97091837],
        [-0.28954082]]),
 array([[0.95943878]]))

In [46]:
test = p2.load_review_data("./lab3_data/reviews.tsv")
text = []
review_labels = np.array([np.zeros(len(test))])
for stuff in test:
    text.append(stuff["text"])
for i in range(len(test)):
    review_labels[0, i] = test[i]["sentiment"]
rah = p2.bag_of_words(text)
review_data = p2.extract_bow_feature_vectors(text, rah)

In [41]:
rev = p2.reverse_dict(rah)
rev

{0: 'i',
 1: 'bought',
 2: 'this',
 3: 'product',
 4: ',',
 5: 'because',
 6: 'it',
 7: "'",
 8: 's',
 9: 'slightly',
 10: 'less',
 11: 'expensive',
 12: 'per',
 13: 'packet',
 14: 'than',
 15: 'the',
 16: 'truvia',
 17: 'brand',
 18: 'only',
 19: 'to',
 20: 'discover',
 21: 'much',
 22: 'sweet',
 23: 'making',
 24: 'more',
 25: 'use',
 26: '.',
 27: 'worse',
 28: 'yet',
 29: 'doesn',
 30: 't',
 31: 'taste',
 32: 'as',
 33: 'good',
 34: 'me',
 35: 'or',
 36: 'for',
 37: 'those',
 38: 'looking',
 39: 'replace',
 40: 'sucralose',
 41: 'splenda',
 42: 'its',
 43: 'bitter',
 44: 'aftertaste',
 45: 'lowers',
 46: 'level',
 47: 'of',
 48: 'saccharine',
 49: 'unless',
 50: 'your',
 51: 'dog',
 52: 'is',
 53: 'younger',
 54: 'and',
 55: 'has',
 56: 'great',
 57: 'teeth',
 58: 'do',
 59: 'not',
 60: 'recommend',
 61: 'you',
 62: 'try',
 63: 'these',
 64: 'they',
 65: 'are',
 66: 'extremely',
 67: 'hard',
 68: 'wouldn',
 69: 'a',
 70: 'celiac',
 71: 'buyer',
 72: 'few',
 73: 'products',
 74: 'ha

In [48]:
# print(review_labels.shape)
# print(review_data.shape)

# review_labels[:, 1:2]
#print(p2.xval_learning_alg(p2.perceptron, review_data, review_labels, 10))
#print(p2.xval_learning_alg(p2.averaged_perceptron, review_data, review_labels, 10))

#p2.averaged_perceptron(review_data, review_labels)
th = p2.averaged_perceptron(review_data, review_labels)[0]

In [43]:
ind = np.argpartition(-1*th[:, 0], -10)[-10:]
ans = []
for i in ind:
    ans.append(rev[i])
ans

['formula',
 'poor',
 'bland',
 'unfortunately',
 'disappointment',
 'stuck',
 'changed',
 'awful',
 'horrible',
 'worst']

In [59]:
th[:, 0]
cur = np.zeros(review_data.shape[1])
for i in range(review_data.shape[1]):
    cur[i] = np.dot(th[:, 0], review_data[:, i])
idx = np.argmax(cur)
print(test[idx]["text"])
idx = np.argmin(cur)
print(test[idx]["text"])

My boyfriend and I received the Keurig Elite brewer as a Christmas gift after lusting after the brewers all of my friends and family owned.  We have been using a trusty Cuisinart 10-cup drip brewer for a couple of years now, and while it has served us well, it was a challenge to get a consistent cup of coffee.  Somehow we always ended up on either the too-strong or two-weak side of the line, despite our best efforts to be consistent.<br /><br />I should mention that we are students living on a very strict budget and we knew that the Keurig would end up being a little bit more costly than our Cuisinart.  But we really liked the idea of brewing coffee a cup at a time and cutting down on waste.  Thankfully, my generous sister surprised us with one for Christmas and it has really turned out to be a perfect gift!<br /><br />WARNING!<br /><br />I feel it is important to mention that we almost sent this back.  Considering how I've been singing its praises, I'm sure this is surprising, but the

In [89]:
def row_avg(x):
    return np.array([np.average(x, axis=1)]).T
def col_avg(x):
    return np.array([np.average(x, axis=0)]).T
def top_bot(x):
    m, n = x.shape
    arr = row_avg(x)
    ret = np.zeros((2, 1))
    sum = 0
    for i in range(m//2):
        sum += arr[i, 0]
    ret[0, 0] = sum/(m//2)
    for i in range(m//2, m):
        sum += arr[i, 0]
    ret[1, 0] = sum/(m-m//2)
    return ret

In [100]:
labels = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
bruh = p2.load_mnist_data(labels)
x = [0, 2, 6, 9]
y = [1, 4, 8, 0]
for j in range(4):
    data = np.zeros((28, len(bruh[x[j]]["images"])+len(bruh[y[j]]["images"])))
    labels = np.zeros((1, len(bruh[x[j]]["images"])+len(bruh[y[j]]["images"])))
    for i in range(len(bruh[x[j]]["images"])):
        data[:, i] = col_avg(bruh[x[j]]["images"][i]).reshape(28,)
        labels[0, i] = -1
    for i in range(len(bruh[y[j]]["images"])):
        data[:, i+len(bruh[x[j]]["images"])] = col_avg(bruh[y[j]]["images"][i]).reshape(28,)
        labels[0, i+len(bruh[x[j]]["images"])] = 1
    print(p2.get_classification_accuracy(data, labels))

0.6375
0.49749999999999994
0.52125
0.5041666666666667


In [94]:
col_avg(bruh[0]["images"][0]).shape

(28, 1)